FIXME: rpm: Include ld in libvirt-devel image
This should help with the

  libc-2.28.so: undefined reference to `_dl_fatal_printf@GLIBC_PRIVATE'

errors that we're hitting since switching to CentOS Stream 8.

If so, we'll have to figure out how to convince bazeldnf to add
these entries itself.

Signed-off-by: Andrea Bolognani <abologna@redhat.com>